In [ ]:
import torch

emb_dim = 300                
hid_dim = 1024              
num_layers = 3               
dropout_rate = 0.45 


param ={"emb_dim":emb_dim ,"hid_dim":hid_dim ,"num_layers":num_layers,"dropout_rate" :dropout_rate}

torch.save(param,"param.pt")


In [ ]:

param = torch.load("vocab.pt")

print(param)

print(param["vocab_size"])

In [1]:
original_str = "def sasa():\n\n       n=0\n       return n"
modified_str = original_str.replace('\n', '<br>')
print(modified_str)


def sasa():<br><br>       n=0<br>       return n


In [1]:
import torch
params_path = "model/params.pt"
params = torch.load(params_path)
print(params)

c:\Users\ASUS\anaconda3\envs\torch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


{'vocab_size': 52229, 'emb_dim': 150, 'hid_dim': 1024, 'num_layers': 2, 'dropout_rate': 0.4}


In [2]:

params['vocab_size'] = 54996
print(params)
torch.save(params,params_path)

{'vocab_size': 54996, 'emb_dim': 150, 'hid_dim': 1024, 'num_layers': 2, 'dropout_rate': 0.4}


In [ ]:
vocab_size = len(vocab)
emb_dim = 150               # 400 in the paper
hid_dim = 1024                # 1150 in the paper
num_layers = 2                # 3 in the paper
dropout_rate = 0.4              
lr = 1e-3  

In [3]:
"asdssdf sadf    ".strip()

'asdssdf sadf'

In [23]:
from transformers import AutoTokenizer
import torch
tokenizer = AutoTokenizer.from_pretrained("model/code-search-net-tokenizer-mod")

params_path = "model/param.pt"

OUTPUT_DIM = tokenizer.vocab_size + len(tokenizer.all_special_tokens)

HID_DIM = 256

DEC_LAYERS = 3

DEC_HEADS = 8

DEC_PF_DIM = 512

DEC_DROPOUT = 0.37

TRG_PAD_IDX = tokenizer.pad_token_id

params = {"OUTPUT_DIM":OUTPUT_DIM,"HID_DIM":HID_DIM ,"DEC_LAYERS":DEC_LAYERS,"DEC_HEADS":DEC_HEADS ,"DEC_PF_DIM":DEC_PF_DIM,"DEC_DROPOUT" :DEC_DROPOUT, "TRG_PAD_IDX":TRG_PAD_IDX}
torch.save(params,params_path)

In [24]:
from utils.models_architect import Decoder

save_path = "model/best_Decoder.pt"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = Decoder( params["OUTPUT_DIM"], params["HID_DIM"],params["DEC_LAYERS"], params["DEC_HEADS"],
                params["DEC_PF_DIM"], params["DEC_DROPOUT"], device, params["TRG_PAD_IDX"])

model.load_state_dict(torch.load(save_path))



<All keys matched successfully>

In [25]:
model.to(device)

Decoder(
  (pos_emb): Embedding(130, 256)
  (trg_emb): Embedding(32772, 256)
  (dropout): Dropout(p=0.37, inplace=False)
  (layers): ModuleList(
    (0): DecoderLayer(
      (norm_att): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (norm_ff): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (norm_maskedatt): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (multi_masked): MultiHeadAttentionLayer(
        (fc_q): Linear(in_features=256, out_features=256, bias=True)
        (fc_k): Linear(in_features=256, out_features=256, bias=True)
        (fc_v): Linear(in_features=256, out_features=256, bias=True)
        (fc): Linear(in_features=256, out_features=256, bias=True)
        (dropout): Dropout(p=0.37, inplace=False)
      )
      (ff): PositionwiseFeedforwardLayer(
        (fc1): Linear(in_features=256, out_features=512, bias=True)
        (fc2): Linear(in_features=512, out_features=256, bias=True)
        (dropout): Dropout(p=0.37, inplace=False)
    

In [84]:
trg_text ="import matplotlib.pyplot as"
tokenized =tokenizer(trg_text)["input_ids"]

In [85]:
trg =torch.LongTensor([tokenizer.bos_token_id]+tokenized).reshape(1,-1)

In [86]:
trg,trg.shape

(tensor([[32770,   646,  8027,    14, 13563,   465]]), torch.Size([1, 6]))

In [87]:
trg=trg.to(device)

In [88]:
with torch.no_grad():
    output= model(trg)
output

tensor([[[-12.3374,  -1.1788,   2.0753,  ..., -12.3273, -12.3996,  -6.5025],
         [-15.5996,  -3.2054,  -2.2044,  ..., -15.5657, -15.3228, -12.5837],
         [-17.5993,  -0.8993,   1.6083,  ..., -17.9851, -17.7867, -13.4420],
         [-16.7966,  -3.6326,  -4.0517,  ..., -17.2331, -16.9205, -13.8225],
         [-18.1991,   1.8396,   3.7016,  ..., -18.3652, -17.6390,  -7.9669],
         [-17.6584,  -4.5549,  -2.7929,  ..., -17.4542, -17.2802, -14.5661]]],
       device='cuda:0')

In [125]:
trg.detach()
trg

tensor([[32770,   646,  8027,    14, 13563,   465,  4488,   199,   646,  8027,
            14, 13563,   465,  4488,   199,   646,  2680,   465,   980,   199,
           504,  8027,    14, 13563,   465,  4488,   199,   504,  6357,    14,
          7120,   492,  4488,   199,   504,  6357,    14,  7120,   492,  9229,
           199,   504,  6357,    14,  7120,   492,  6904,   199,   504,  6357,
            14,  1238,   492,  6904,   199,   504,  6357,    14, 12281,   492,
          1852,    63,  7120,    12,  1852,    63, 21893,   199,   504,  6357,
            14,  6676,    63,  1238,   492, 27903,   199,   504,  6357,    14,
          1208]], device='cuda:0')

In [128]:

def suggestor(prompt,model,tokenizer,max_lenght=130):
    tokenized =tokenizer(prompt)["input_ids"]
    trg =torch.LongTensor([tokenizer.bos_token_id]+tokenized).reshape(1,-1)
    trg=trg.to(device)
    with torch.no_grad():
        for i in range(max_lenght):
            output= model.greedy_decode(trg)
            trg = torch.cat((trg, output[-1].reshape(1,-1)), dim=1)

            if output[-1] == tokenizer.eos_token_id:
                break
    result = tokenizer.decode(trg.squeeze(0),skip_special_tokens=True)
    trg.detach()

    return result

prompt = "import numpy"
print(suggestor(prompt,model,tokenizer))

import numpy as np
import matplotlib.pyplot as plt


import matplotlib.pyplot as plt
from sklearn.ticker import=matplotlib.pyplot as plt.subplot
from sklearn.linear import matplotlib.pyplot as plt
from sklearn.semilogx = plt.rcParams['xtick.rcParams']['text.rcParams']['usetex']

from sklearn.rcParams['figure.grid_size'] = 'xtick.size'


plt.figure.rcParams['font.size'] = plt.rcParams['font_size']
plt.rcParams['font.font.rc


In [120]:
trg.squeeze(0).shape

torch.Size([21])

In [116]:
trg

tensor([[32770,   646,  8027,    14, 13563,   465,  4488,   199,   646,  8027,
            14, 13563,   465,  4488,   199,   646,  2680,   465,   980,   199,
           504]], device='cuda:0')

In [109]:
trg

tensor([[32770,   646,  8027,    14, 13563,   465]], device='cuda:0')

In [110]:
output[-1]

tensor(4488, device='cuda:0')

In [112]:
output[-1].reshape(1,-1)

tensor([[4488]], device='cuda:0')

In [113]:
c = torch.cat((trg, output[-1].reshape(1,-1)), dim=1)

In [114]:
c

tensor([[32770,   646,  8027,    14, 13563,   465,  4488]], device='cuda:0')

In [90]:
trg_text + tokenizer.decode(output[-1],skip_special_tokens=True)

'import matplotlib.pyplot as plt'

In [91]:
prediction= model(trg)
prediction = prediction.squeeze(0)
prediction = prediction # not include first one? 
prediction = prediction.argmax(1) 

In [92]:
trg_text + tokenizer.decode(output[-1],skip_special_tokens=True)

'import matplotlib.pyplot as plt'